### ISSUE TITLE
Use of angle brackets around file names for include statements

### ISSUE THREAD

**Issue by elfring** [cbeck88/spirit-po#1]
Would you like to [replace any double quotes](https://github.com/cbeck88/spirit-po/blob/3a2b399f5ceda472076409d63fe01353b4de58a5/include/spirit_po.hpp#L8) by [angle brackets around file names for include statements](http://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename)?

**Comment by cbeck88** [comment]
Thanks for pointing this out!

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/cbeck88/spirit-po/commit/bcc099a9fa26053d741e170363d8d20d884f5510).

**Comment by cbeck88** [comment]
Yeah... I'm not sure if it's strictly buggy if you don't do this, for instance, if you look in the well-known "asio" library, they don't do this with their internal headers. https://github.com/chriskohlhoff/asio/tree/master/asio/include/asio

But boost does it, so I think it makes sense to follow suit here also. Thanks for pointing it out!
