### ISSUE TITLE
MSVC Compile Warning

### ISSUE THREAD

**Issue by vasek-cz** [cbeck88/spirit-po#4]
Warning C4005 when compiling `catalog_metadata.hpp` under MSVC (and wingdi.h included):

> ... include\spirit_po\catalog_metadata.hpp(69): warning C4005: 'DEFAULT_CHARSET': macro redefinition
> c:\program files (x86)\windows kits\8.1\include\um\wingdi.h(1587): note: see previous definition of 'DEFAULT_CHARSET'

**Comment by cbeck88** [comment]
Should be fixed after this commit on master, please let me know:

https://github.com/cbeck88/spirit-po/commit/cdf110bb535721bc3dc52e4d118483c5091893bd

Thanks for report!

**Comment by vasek-cz** [comment]
Fixed, thanks!
