### ISSUE TITLE
Test if string is in catalog

### ISSUE THREAD

**Issue by beutlich** [cbeck88/spirit-po#7]
Would be helpful if there was a test to see if a string is in the catalog, since gettext etc. always return the original string if there is no translation. I know, that I can use get_hashmap() or gettext_line_no(), but be more convenient, if gettext returns a std:pair<string, bool> where the second value indicates if the string is translated or not.

**Comment by beutlich** [comment]
My proposal for the gettext variants:

```cpp
  const char * gettext_try(const char * msgid) const {
    const auto it = hashmap_.find(msgid);
    if (it != hashmap_.cend()) {
      return this->get(it->second).c_str();
    }
    else {
      return nullptr;
    }
  }

  template <typename S>
  std::pair<std::string, bool> gettext_str_impl_try(S && msgid) const {
    const auto it = hashmap_.find(msgid);
    if (it != hashmap_.cend()) {
      return std::make_pair(this->get(it->second), true);
    }
    else {
      return std::make_pair("", false);
    }
  }
```

Let me know what you think and I can create PR for it.

**Comment by cbeck88** [comment]
what's your use-case for this? you have special fallback behavior you want to use instead?

i'd be tempted to go with an api like `contains_msgid(const char * msgid) -> bool`
rather than return nullptr from some of the functions, given that gettext normally never returns a null pointer.

**Comment by beutlich** [comment]
In our use-case we need to differ if the returned translated string is a true translation or not. If it is not a true translation we need to check in different cataloges as fallback.

Meanwhile, we have been using the proposed `gettext_try` variants and got the desired behaviour. For us it was more convenient to have it in a single call, instead of calling another funtion `contains_msgid`. But this likely is matter of taste. Thank you anyway!
